### ISSUE TITLE
ORDEIG of propagator

### ISSUE THREAD

**Issue by shifanmao** [qmacAstanford/MultiPointCalculation#2]
ORDEIG is not always consistent with length of propagator.eig

This happens when mu > 0. Example
`
mu = 2
prop4 = propagator.propagator(name,1.0*K[ii],mu,nlam=nlam)
print(len(prop4.eig))
print(prop4.ORDEig)
`

**Comment by qmacAstanford** [comment]
I have corrected the sums so that they go from mu-ORDEig instead of 0-ORDDEig.  I believe this fixed the problem.  Am I correct?

**Comment by qmacAstanford** [comment]
Now I actually have fixed this problem.  The first mu-1 values are NaN.  The length is ORDEig.
Thanks for catching this.
